### ISSUE TITLE
rejected from app store due to disallowed file 'Frameworks'

### ISSUE THREAD

**Issue by ekimia** [iziz/libPhoneNumber-iOS#114] opened 2016-01-07 01:14 UTC
Installed via carthage, here's what i got:
<img width="691" alt="screen shot 2016-01-06 at 8 15 01 pm" src="https://cloud.githubusercontent.com/assets/357513/12159673/34c0ae86-b4b2-11e5-8d11-14eb98edc94f.png">

**Comment by kballard** [comment] 2016-01-07 21:54
This is because the project specifies `EMBEDDED_CONTENT_CONTAINS_SWIFT = YES` for the libPhoneNumber-iOS target. It shouldn't do this.

**Comment by ekimia** [comment] 2016-01-08 17:22
PR https://github.com/iziz/libPhoneNumber-iOS/pull/115

**Comment by iziz** [comment] 2016-01-12 05:10
Merged it. and I will remove .swift file.

**Closed by iziz** 2016-01-12 05:10 UTC

**Comment by tbugrara** [comment] 2016-01-20 21:40
Having same problem. I'm using carthage and pulling libPhoneNumber-iOS at commit 60602, which seems like it should have the fix? Still getting the same exact error though. Am I missing something?

**Comment by kballard** [comment] 2016-01-21 01:52
@tbugrara Carthage has a bug where it doesn't clean built products when rebuilding (version 0.12 will fix it). Open up Xcode, go to the Window->Projects menu, find the project for libPhoneNumber-iOS, and delete the derived data.

**Comment by dpassage** [comment] 2016-02-06 00:01
Any plan for a new release to include this fix and I'm sure others?

**Comment by crontab** [comment] 2016-02-06 00:07
Because 3rd party frameworks are not allowed on App Store, the only solution is to link the library statically. I have an Xcode project file that builds a static libPhoneNumber library (with a small fix recently incorporated from my fork). If iziz doesn't mind I'll do a pull request with this project file.

**Comment by kballard** [comment] 2016-02-08 00:22
@crontab That's completely wrong. As of iOS 8, apps can (and a great many do) include dynamic frameworks in their app bundle.

The problem is that frameworks cannot themselves include other frameworks, and that's what the reported error was showing.
